### ISSUE TITLE
about project

### ISSUE THREAD

**Issue by dwiprasetyo1506** [sheillendra/yii2-jeasyui#10]
Terima kasih sebelumnya, saya tertarik dengan yii- jeasy ui nya,

Suhu mau tanya dong untuk jalankan nya saya harus melakukan apa lagi,
sy sudah download dan sy put on my xampp/htdocs

dan running seperti di bawha ini :

![howto_running_yii-jeasyui](https://user-images.githubusercontent.com/46664581/51096706-1ba70a80-17f1-11e9-986f-71baebbd67ec.jpg)

**Comment by sheillendra** [comment]
ini extension tema, kamu harus install yii2 framework dulu sebagai aplikasi utama.
