### ISSUE TITLE
Problem Install

### ISSUE THREAD

**Issue by atmanegara** [sheillendra/yii2-jeasyui#5]
Saya coba install via composer, add require "sheillendra/yii2-jeasyui": "dev-master", dan terjadi error mas
`
  Problem 1
    - Installation request for sheillendra/yii2-jeasyui dev-master -> satisfiabl
e by sheillendra/yii2-jeasyui[dev-master].
    - sheillendra/yii2-jeasyui dev-master requires sheillendra/yii2-helpers \* ->
 no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your min
  imum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more det
  ails.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further commo
n problems.`

mohon pencerahannya mas

**Comment by sheillendra** [comment]
minimun-stability di composer.json nya kamu harus dev, seperti ini "minimum-stability": "dev", kalau stable ganti ke dev. kalau itu belum berhasil juga, hapus composer.lock lebih dulu.

kadang kualitas jaringan juga mempengaruhi

**Comment by atmanegara** [comment]
klo saya ganti ke dev apa ga ngaruh yang lain yang versi stable mas :), malah nanti ikut terupdate juga ama versi ke dev ,atau sebagian ke beta , padahal sebelumnya udah stable :),tp saya akan coba mas, makasih

**Comment by atmanegara** [comment]
sukses install mas , yii jadi ikut ke update ke 2.0.8 dev

**Comment by sheillendra** [comment]
kalau mau tetap stabil, sertakan versi stable dari repo yang dimaksud, contohnya untuk yii, kode berikut di composer.json akan mengambil yii2 dari yiisoft versi stabil dari versi terbaru atau paling tidak versi 2.0.7 

```
 "yiisoft/yii2" : "~2.0.7"
```

untuk repo saya ini, belum stabil, sementara ada perubahan, untuk mengikuti best practice dari yii2, maaf ya, tunggu updatenya
