### ISSUE TITLE
Instalasi di YII2 Advance

### ISSUE THREAD

**Issue by oche8080** [sheillendra/yii2-jeasyui#7]
terjadi error seperti ini

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for sheillendra/yii2-jeasyui dev-master -> satisfiable by sheillendra/yii2-jeasyui[dev-master].
    - sheillendra/yii2-jeasyui dev-master requires sheillendra/yii2-helpers * -> satisfiable by sheillendra/yii2-helpers[dev-master] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by sheillendra** [comment]
bisa lihat composer.json nya?

kalau tidak gunakan versi v2.0.0-rc.2, karena yang dev masih belum stabil
